//Generated by Gemini 3.8 Thinking:
//https://gemini.google.com/share/d/1xsqFvhObDFKd1l2fiS7u99dTPOLORBQ_?usp=sharing

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
#include <stdalign.h>

void kernel
(
  int              m,
  int              n,
  int              k,
  double* restrict a,
  double* restrict b,
  double* restrict c
){
  // Initialize 12 AVX2 accumulators for the 8x6 tile of C
  __m256d c0_0 = _mm256_setzero_pd(); __m256d c1_0 = _mm256_setzero_pd();
  __m256d c0_1 = _mm256_setzero_pd(); __m256d c1_1 = _mm256_setzero_pd();
  __m256d c0_2 = _mm256_setzero_pd(); __m256d c1_2 = _mm256_setzero_pd();
  __m256d c0_3 = _mm256_setzero_pd(); __m256d c1_3 = _mm256_setzero_pd();
  __m256d c0_4 = _mm256_setzero_pd(); __m256d c1_4 = _mm256_setzero_pd();
  __m256d c0_5 = _mm256_setzero_pd(); __m256d c1_5 = _mm256_setzero_pd();

  const double* restrict a_ptr = a;
  const double* restrict b_ptr = b;

  int p = 0;

  // Unroll loop by 4x along the k dimension
  for (; p <= k - 4; p += 4) {
    // --- Step p + 0 ---
    {
      __m256d a0 = _mm256_load_pd(a_ptr + 0);
      __m256d a1 = _mm256_load_pd(a_ptr + 4);

      c0_0 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[0]), c0_0);
      c1_0 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[0]), c1_0);

      c0_1 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[1]), c0_1);
      c1_1 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[1]), c1_1);

      c0_2 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[2]), c0_2);
      c1_2 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[2]), c1_2);

      c0_3 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[3]), c0_3);
      c1_3 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[3]), c1_3);

      c0_4 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[4]), c0_4);
      c1_4 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[4]), c1_4);

      c0_5 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[5]), c0_5);
      c1_5 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[5]), c1_5);

      a_ptr += 8;
      b_ptr += 6;
    }

    // --- Step p + 1 ---
    {
      __m256d a0 = _mm256_load_pd(a_ptr + 0);
      __m256d a1 = _mm256_load_pd(a_ptr + 4);

      c0_0 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[0]), c0_0);
      c1_0 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[0]), c1_0);

      c0_1 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[1]), c0_1);
      c1_1 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[1]), c1_1);

      c0_2 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[2]), c0_2);
      c1_2 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[2]), c1_2);

      c0_3 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[3]), c0_3);
      c1_3 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[3]), c1_3);

      c0_4 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[4]), c0_4);
      c1_4 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[4]), c1_4);

      c0_5 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[5]), c0_5);
      c1_5 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[5]), c1_5);

      a_ptr += 8;
      b_ptr += 6;
    }

    // --- Step p + 2 ---
    {
      __m256d a0 = _mm256_load_pd(a_ptr + 0);
      __m256d a1 = _mm256_load_pd(a_ptr + 4);

      c0_0 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[0]), c0_0);
      c1_0 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[0]), c1_0);

      c0_1 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[1]), c0_1);
      c1_1 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[1]), c1_1);

      c0_2 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[2]), c0_2);
      c1_2 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[2]), c1_2);

      c0_3 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[3]), c0_3);
      c1_3 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[3]), c1_3);

      c0_4 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[4]), c0_4);
      c1_4 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[4]), c1_4);

      c0_5 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[5]), c0_5);
      c1_5 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[5]), c1_5);

      a_ptr += 8;
      b_ptr += 6;
    }

    // --- Step p + 3 ---
    {
      __m256d a0 = _mm256_load_pd(a_ptr + 0);
      __m256d a1 = _mm256_load_pd(a_ptr + 4);

      c0_0 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[0]), c0_0);
      c1_0 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[0]), c1_0);

      c0_1 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[1]), c0_1);
      c1_1 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[1]), c1_1);

      c0_2 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[2]), c0_2);
      c1_2 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[2]), c1_2);

      c0_3 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[3]), c0_3);
      c1_3 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[3]), c1_3);

      c0_4 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[4]), c0_4);
      c1_4 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[4]), c1_4);

      c0_5 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[5]), c0_5);
      c1_5 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[5]), c1_5);

      a_ptr += 8;
      b_ptr += 6;
    }
  }

  // Remainder loop for any leftover k iterations
  for (; p < k; ++p) {
    __m256d a0 = _mm256_load_pd(a_ptr + 0);
    __m256d a1 = _mm256_load_pd(a_ptr + 4);

    c0_0 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[0]), c0_0);
    c1_0 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[0]), c1_0);

    c0_1 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[1]), c0_1);
    c1_1 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[1]), c1_1);

    c0_2 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[2]), c0_2);
    c1_2 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[2]), c1_2);

    c0_3 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[3]), c0_3);
    c1_3 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[3]), c1_3);

    c0_4 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[4]), c0_4);
    c1_4 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[4]), c1_4);

    c0_5 = _mm256_fmadd_pd(a0, _mm256_set1_pd(b_ptr[5]), c0_5);
    c1_5 = _mm256_fmadd_pd(a1, _mm256_set1_pd(b_ptr[5]), c1_5);

    a_ptr += 8;
    b_ptr += 6;
  }

  // Optimized writeback: Store accumulated values into stack buffer and write to C
  alignas(32) double buf0[4], buf1[4];
  __m256d c0_acc[6] = {c0_0, c0_1, c0_2, c0_3, c0_4, c0_5};
  __m256d c1_acc[6] = {c1_0, c1_1, c1_2, c1_3, c1_4, c1_5};

  for (int j = 0; j < 6; ++j) {
    _mm256_store_pd(buf0, c0_acc[j]);
    _mm256_store_pd(buf1, c1_acc[j]);

    c[0 * 6 + j] = buf0[0];
    c[1 * 6 + j] = buf0[1];
    c[2 * 6 + j] = buf0[2];
    c[3 * 6 + j] = buf0[3];

    c[4 * 6 + j] = buf1[0];
    c[5 * 6 + j] = buf1[1];
    c[6 * 6 + j] = buf1[2];
    c[7 * 6 + j] = buf1[3];
  }
}